
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EDM_DB
{

using System;
    using System.Collections.Generic;
    
public partial class default_tbChucNang
{

    public int Stt { get; set; }

    public System.Guid IdChucNang { get; set; }

    public string MaChucNang { get; set; }

    public string TenChucNang { get; set; }

    public Nullable<int> SoThuTu { get; set; }

    public string Icon { get; set; }

    public Nullable<System.Guid> IdCha { get; set; }

    public Nullable<int> CapDo { get; set; }

    public Nullable<int> TrangThai { get; set; }

    public Nullable<System.Guid> MaDonViSuDung { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<System.Guid> IdNguoiTao { get; set; }

    public Nullable<System.DateTime> NgaySua { get; set; }

    public Nullable<System.Guid> IdNguoiSua { get; set; }

}

}
