

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EDM_DB
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class EDM_DBEntities : DbContext
{
    public EDM_DBEntities()
        : base("name=EDM_DBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<default_tbChucNang> default_tbChucNang { get; set; }

    public virtual DbSet<default_tbChucNang_ThaoTac> default_tbChucNang_ThaoTac { get; set; }

    public virtual DbSet<default_tbChucVu> default_tbChucVu { get; set; }

    public virtual DbSet<default_tbQuocGia> default_tbQuocGia { get; set; }

    public virtual DbSet<tbBaiDang> tbBaiDangs { get; set; }

    public virtual DbSet<tbBaiDangTepDinhKem> tbBaiDangTepDinhKems { get; set; }

    public virtual DbSet<tbChienDich> tbChienDiches { get; set; }

    public virtual DbSet<tbCoCauToChuc> tbCoCauToChucs { get; set; }

    public virtual DbSet<tbDonViSuDung> tbDonViSuDungs { get; set; }

    public virtual DbSet<tbDonViTien> tbDonViTiens { get; set; }

    public virtual DbSet<tbKieuNguoiDung> tbKieuNguoiDungs { get; set; }

    public virtual DbSet<tbLichDangBai> tbLichDangBais { get; set; }

    public virtual DbSet<tbLichDangBaiChiTiet> tbLichDangBaiChiTiets { get; set; }

    public virtual DbSet<tbLichSuDangBai> tbLichSuDangBais { get; set; }

    public virtual DbSet<tbNenTang> tbNenTangs { get; set; }

    public virtual DbSet<tbNguoiDung> tbNguoiDungs { get; set; }

    public virtual DbSet<tbNoiDung> tbNoiDungs { get; set; }

    public virtual DbSet<tbTepDinhKem> tbTepDinhKems { get; set; }


    public virtual ObjectResult<Lay_TruongDuLieus_Result> Lay_TruongDuLieus(Nullable<int> maDonViSuDung)
    {

        var maDonViSuDungParameter = maDonViSuDung.HasValue ?
            new ObjectParameter("maDonViSuDung", maDonViSuDung) :
            new ObjectParameter("maDonViSuDung", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lay_TruongDuLieus_Result>("Lay_TruongDuLieus", maDonViSuDungParameter);
    }


    public virtual int XoaDuLieuDatabase(Nullable<int> maDonViSuDung)
    {

        var maDonViSuDungParameter = maDonViSuDung.HasValue ?
            new ObjectParameter("maDonViSuDung", maDonViSuDung) :
            new ObjectParameter("maDonViSuDung", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaDuLieuDatabase", maDonViSuDungParameter);
    }

}

}

