
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EDM_DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbAITool
{

    public int Stt { get; set; }

    public System.Guid IdAITool { get; set; }

    public string ToolCode { get; set; }

    public string ToolName { get; set; }

    public string ApiEndpoint { get; set; }

    public string Model { get; set; }

    public string APIKey { get; set; }

    public string AdditionalHeaders { get; set; }

    public string RequestBodyTemplate { get; set; }

    public Nullable<bool> IsEncrypted { get; set; }

    public string GhiChu { get; set; }

    public Nullable<int> TrangThai { get; set; }

    public Nullable<System.Guid> MaDonViSuDung { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<System.Guid> IdNguoiTao { get; set; }

    public Nullable<System.DateTime> NgaySua { get; set; }

    public Nullable<System.Guid> IdNguoiSua { get; set; }

}

}
