
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EDM_DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbDonViSuDung
{

    public int Stt { get; set; }

    public System.Guid MaDonViSuDung { get; set; }

    public string ThietBiLuuTru { get; set; }

    public string TenDonViSuDung { get; set; }

    public string TenMien { get; set; }

    public string DiaChi { get; set; }

    public string SoDienThoai { get; set; }

    public string Email { get; set; }

    public string Logo { get; set; }

    public string Banner { get; set; }

    public string TieuDeTrangChu { get; set; }

    public string GiaoDien { get; set; }

    public Nullable<bool> SuDungTrangNguoiDung { get; set; }

    public Nullable<int> TrangThai { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<System.Guid> IdNguoiTao { get; set; }

    public Nullable<System.DateTime> NgaySua { get; set; }

    public Nullable<System.Guid> IdNguoiSua { get; set; }

}

}
