
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EDM_DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbKhachHang
{

    public int Stt { get; set; }

    public System.Guid IdKhachHang { get; set; }

    public Nullable<System.Guid> IdTrangThaiHoc { get; set; }

    public Nullable<System.Guid> IdTrangThaiChamSoc { get; set; }

    public Nullable<System.Guid> IdLoaiKhachHang { get; set; }

    public Nullable<System.Guid> IdGoiChamSoc { get; set; }

    public Nullable<System.Guid> IdQuocGiaSinhSong { get; set; }

    public Nullable<System.Guid> IdPhuongThucThanhToan { get; set; }

    public string TenKhachHang { get; set; }

    public string Email { get; set; }

    public string LienKet { get; set; }

    public string LienKetSale { get; set; }

    public string SoDienThoai { get; set; }

    public Nullable<int> DoTuoi { get; set; }

    public string NgheNghiep { get; set; }

    public string NguonKhachHang { get; set; }

    public string DiaChi { get; set; }

    public string QuyenTruyCap { get; set; }

    public string GhiChu { get; set; }

    public Nullable<int> TrangThai { get; set; }

    public Nullable<System.Guid> MaDonViSuDung { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<System.Guid> IdNguoiTao { get; set; }

    public Nullable<System.DateTime> NgaySua { get; set; }

    public Nullable<System.Guid> IdNguoiSua { get; set; }

}

}
