
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EDM_DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbKhachHang_DonHang_ThanhToan
{

    public int Stt { get; set; }

    public System.Guid IdThanhToan { get; set; }

    public Nullable<System.Guid> IdDonViTien { get; set; }

    public Nullable<System.Guid> IdDonHang { get; set; }

    public Nullable<System.Guid> IdKhachHang { get; set; }

    public Nullable<System.Guid> IdSanPham { get; set; }

    public Nullable<int> ThuTuThanhToan { get; set; }

    public Nullable<int> SoTienDaDong_ChuaQuyDoi { get; set; }

    public Nullable<int> SoTienDaDong { get; set; }

    public Nullable<decimal> PhanTramDaDong { get; set; }

    public string GhiChu { get; set; }

    public Nullable<int> TrangThai { get; set; }

    public Nullable<System.Guid> MaDonViSuDung { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<System.Guid> IdNguoiTao { get; set; }

    public Nullable<System.DateTime> NgaySua { get; set; }

    public Nullable<System.Guid> IdNguoiSua { get; set; }

}

}
