
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EDM_DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbLichSuTruyCap
{

    public int Stt { get; set; }

    public System.Guid IdLichSuTruyCap { get; set; }

    public Nullable<System.Guid> IdNguoiDung { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public string TenModule { get; set; }

    public string ThaoTac { get; set; }

    public string NoiDungChiTiet { get; set; }

    public Nullable<System.Guid> MaDonViSuDung { get; set; }

}

}
