
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EDM_DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbLopHoc_BuoiHoc
{

    public int Stt { get; set; }

    public System.Guid IdLopHoc_BuoiHoc { get; set; }

    public Nullable<System.Guid> IdLopHoc { get; set; }

    public string IdGiaoVien { get; set; }

    public string IdKhachHang { get; set; }

    public string IdDonHang { get; set; }

    public Nullable<int> LuongTheoBuoi { get; set; }

    public Nullable<int> ThuTuBuoiHoc { get; set; }

    public Nullable<System.DateTime> ThoiGianBatDau { get; set; }

    public Nullable<int> ThoiLuong { get; set; }

    public Nullable<int> DiemDanh { get; set; }

    public string GhiChu { get; set; }

    public Nullable<int> TrangThai { get; set; }

    public Nullable<System.Guid> MaDonViSuDung { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<System.Guid> IdNguoiTao { get; set; }

    public Nullable<System.DateTime> NgaySua { get; set; }

    public Nullable<System.Guid> IdNguoiSua { get; set; }

}

}
