
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EDM_DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbNguoiDung
{

    public int Stt { get; set; }

    public System.Guid IdNguoiDung { get; set; }

    public Nullable<System.Guid> IdCoCauToChuc { get; set; }

    public Nullable<System.Guid> IdKieuNguoiDung { get; set; }

    public string TenDangNhap { get; set; }

    public string MatKhau { get; set; }

    public string TenNguoiDung { get; set; }

    public Nullable<bool> GioiTinh { get; set; }

    public string SoTaiKhoanNganHang { get; set; }

    public string LinkLienHe { get; set; }

    public Nullable<int> SoLanDangNhap { get; set; }

    public Nullable<bool> YeuCauDoiMatKhau { get; set; }

    public Nullable<bool> KichHoatGioiThieu { get; set; }

    public Nullable<bool> Online { get; set; }

    public Nullable<bool> KichHoat { get; set; }

    public string Email { get; set; }

    public string SoDienThoai { get; set; }

    public Nullable<System.DateTime> NgaySinh { get; set; }

    public Nullable<System.Guid> IdChucVu { get; set; }

    public Nullable<System.Guid> IdCapDo_DoanhThu { get; set; }

    public string GhiChu { get; set; }

    public string ThongTinThietBi_TruyCap { get; set; }

    public Nullable<int> TrangThai { get; set; }

    public Nullable<System.Guid> MaDonViSuDung { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<System.Guid> IdNguoiTao { get; set; }

    public Nullable<System.DateTime> NgaySua { get; set; }

    public Nullable<System.Guid> IdNguoiSua { get; set; }

}

}
